# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: commands.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ommands.proto\x12\x08\x63ommands\"\xfb\x01\n\x06Output\x12\x15\n\x0bstringValue\x18\x01 \x01(\tH\x00\x12\x34\n\x0estringVecValue\x18\x02 \x01(\x0b\x32\x1a.commands.Output.StringVecH\x00\x12\x1b\n\x11optionStringValue\x18\x03 \x01(\tH\x00\x12\x13\n\tboolValue\x18\x04 \x01(\x08H\x00\x12\x14\n\nint64Value\x18\x05 \x01(\x03H\x00\x12,\n\nemptyValue\x18\x06 \x01(\x0b\x32\x16.commands.Output.EmptyH\x00\x1a\x1b\n\tStringVec\x12\x0e\n\x06values\x18\x01 \x03(\t\x1a\x07\n\x05\x45mptyB\x08\n\x06output\"\xc6\x01\n\x0e\x43ommandOutcome\x12\x35\n\x08\x66inished\x18\x01 \x01(\x0b\x32!.commands.CommandOutcome.FinishedH\x00\x12\x37\n\tcancelled\x18\x02 \x01(\x0b\x32\".commands.CommandOutcome.CancelledH\x00\x1a,\n\x08\x46inished\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.commands.Output\x1a\x0b\n\tCancelledB\t\n\x07outcomeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OUTPUT']._serialized_start=29
  _globals['_OUTPUT']._serialized_end=280
  _globals['_OUTPUT_STRINGVEC']._serialized_start=234
  _globals['_OUTPUT_STRINGVEC']._serialized_end=261
  _globals['_OUTPUT_EMPTY']._serialized_start=263
  _globals['_OUTPUT_EMPTY']._serialized_end=270
  _globals['_COMMANDOUTCOME']._serialized_start=283
  _globals['_COMMANDOUTCOME']._serialized_end=481
  _globals['_COMMANDOUTCOME_FINISHED']._serialized_start=413
  _globals['_COMMANDOUTCOME_FINISHED']._serialized_end=457
  _globals['_COMMANDOUTCOME_CANCELLED']._serialized_start=459
  _globals['_COMMANDOUTCOME_CANCELLED']._serialized_end=470
# @@protoc_insertion_point(module_scope)
