# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: progress.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'progress.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprogress.proto\x12\x08progress\"4\n\x05Ticks\x12\r\n\x05\x63ount\x18\x01 \x01(\x04\x12\r\n\x05state\x18\x02 \x01(\t\x12\r\n\x05total\x18\x03 \x01(\x04\"\x99\x01\n\x13LifecycleTransition\x12$\n\x07started\x18\x01 \x01(\x0b\x32\x11.progress.StartedH\x00\x12(\n\x05ticks\x18\x02 \x01(\x0b\x32\x17.progress.TicksWithUuidH\x00\x12$\n\x07stopped\x18\x03 \x01(\x0b\x32\x11.progress.StoppedH\x00\x42\x0c\n\ntransition\"&\n\x07Started\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05\x61lias\x18\x02 \x01(\t\"=\n\rTicksWithUuid\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x1e\n\x05ticks\x18\x02 \x01(\x0b\x32\x0f.progress.Ticks\"\x17\n\x07Stopped\x12\x0c\n\x04uuid\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'progress_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKS']._serialized_start=28
  _globals['_TICKS']._serialized_end=80
  _globals['_LIFECYCLETRANSITION']._serialized_start=83
  _globals['_LIFECYCLETRANSITION']._serialized_end=236
  _globals['_STARTED']._serialized_start=238
  _globals['_STARTED']._serialized_end=276
  _globals['_TICKSWITHUUID']._serialized_start=278
  _globals['_TICKSWITHUUID']._serialized_end=339
  _globals['_STOPPED']._serialized_start=341
  _globals['_STOPPED']._serialized_end=364
# @@protoc_insertion_point(module_scope)
