# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sde.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'sde.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsde.proto\x12\x03sde\"D\n\nSdeRequest\x12\x14\n\nwrite_text\x18\x01 \x01(\tH\x00\x12\x15\n\x0bwrite_bytes\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"\x1c\n\x0bSdeResponse\x12\r\n\x05\x62ytes\x18\x01 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sde_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SDEREQUEST']._serialized_start=18
  _globals['_SDEREQUEST']._serialized_end=86
  _globals['_SDERESPONSE']._serialized_start=88
  _globals['_SDERESPONSE']._serialized_end=116
# @@protoc_insertion_point(module_scope)
